<?
$menu["menu300"] = array (
    array("300000", "게시판관리", ""),
    array("300100", "게시판관리", "$g4[admin_path]/board_list.php"),
    array("300200", "게시판그룹관리", "$g4[admin_path]/boardgroup_list.php"),
    array("300210", "게시판스킨목록", "$g4[admin_path]/board_skin.php"),
    array("-"),
 //   array("300250", "카테고리관리", "$g4[admin_path]/category_list.php"),
 //   array("-"),
    array("300930", "서비스 이용 회원", "$g4[admin_path]/prem_list.php"),
    array("300900", "배너관리", "$g4[admin_path]/banner_list.php"),
    array("300910", "배너그룹관리", "$g4[admin_path]/banner_group_list.php"),
    array("300920", "배너클릭현황", "$g4[admin_path]/banner_click_list.php"),
    array("-"),
 //   array("300110", "최근글정렬", "$g4[admin_path]/board_new_sort.php"),
 //   array("300120", "최근글다시만들기", "$g4[admin_path]/board_new_rebuild.php"),
    array("300150", "DB Cache", "$g4[admin_path]/dbcache_list.php"),
    array("-"),
    array("300700", "휴지통관리", "$g4[admin_path]/recycle_list.php"),
    array("-"),
    array("300800", "이미지관리", "$g4[admin_path]/chimage_list.php"),
    array("300810", "안쓰는이미지관리", "$g4[admin_path]/chimage_unused_list.php"),
 //   array("300820", "썸네일삭제", "$g4[admin_path]/thumb_clear.php?days=90"),
    array("300830", "임시저장글관리", "$g4[admin_path]/tempsave_list.php"),
    array("-"),
    array("300300", "신고관리", "$g4[admin_path]/singo_list.php"),
    array("300310", "신고해제관리", "$g4[admin_path]/unsingo_list.php"),
    array("-"),
    array("300400", "게시글 통계", "$g4[admin_path]/stat_write.php"),
    array("300500", "다운로드내역", "$g4[admin_path]/download_list.php"),
 //   array("-"),
 //   array("300700", "렌탈관리", "$g4[admin_path]/rantal/category_list.php"),
 //   array("300710", "렌탈신청관리", "$g4[admin_path]/rantal/online_list.php"),
 //   array("-"),
 //   array("300600", "유니크로 로그", "$g4[admin_path]/unicro_log.php")
);
?>
